### ISSUE TITLE
Environment variables support

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api-next#129]
Instead of relying on config files, Directus should be able to work from just environment variables. This increases interop with Docker.

---

@WoLfulus We could also consider providing a default config file that uses ` getenv(`DIRECTUS_DB_PASSWORD`)` instead of values. That would give us both with only 1 handler for everything

**Comment by WoLfulus** [comment]
The problem is supporting multitenancy and array values. This is going to be a pain to be honest.

**Comment by WoLfulus** [comment]
Partial support for now
