### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api-next#131]
Should support:

creating config files
creating default tables and data
upgrading the database schema ref #130
~remove logs files~
change a user password

**Comment by jooola** [comment]
May I send a PR with the console interface I created in directus/api ?
Idea it to build the CLI interface before binding to commands to the actual services/actions. So that wa have some overview of the CLI capabilities.

**Comment by rijkvanzanten** [comment]
Sure thing! I've created all these issues as a checklist of "to-dos" / "shouldn't forgets" so everything that's open and not assigned yet is free to pick up 🙂

**Comment by WoLfulus** [comment]
That would be awesome!

I'd love to have commands working on both artisan and a standalone instance (to keep the core framework decoupled from laravel itself).

Any ideas on how we can accomplish that?

**Comment by jooola** [comment]
I think this can be done by running a Illuminate console application on the framework side and import the commands in artisan when running with the full Laravel setup.

We build our commands in lets say `Directus/Console/Commands`.
Those command implements the illuminate command (see https://laravel.com/api/6.x/Illuminate/Console/Command.html).

Then The provider to register these commands to artisan when loading the app into laravel
And we can provide a dump cli package that will run a Illuminate Console application (standalone) (see https://laravel.com/api/6.x/Illuminate/Console/Application.html)

**Comment by jooola** [comment]
Got some inspiration from https://stackoverflow.com/questions/43623227/is-there-a-version-of-laravel-for-console-app-only

**Comment by WoLfulus** [comment]
I've pushed some code with a simple command which just forwards the `artisan vendor:publish`. We can move in that direction since I decided to drop the idea of having a standalone cli for now. Let's keep it simple until we have enough resources to get those implemented.

**Comment by WoLfulus** [comment]
I'm closing this one for now, we can revisit it later

- `creating config files` isn't something we can do right now
- `creating default tables and data` is handled by migrations already
- `upgrading the database schema ref #130` already handled by the above too
- `remove logs files` there should be proper/specific ways to do this within laravel already

I opened #172 to keep track of the user password reset separately
