### ISSUE TITLE
Make models work with a separate system connection

### ISSUE THREAD

**Issue by WoLfulus** [directus/api-next#142]
We need a way to specify that a Model needs to use a specific connection (so we can target them to the system/directus database)

Relates to #141

**Comment by jooola** [comment]
@WoLfulus Could you clarify the needs here ?
I this about running a db connection without the laravel aplication ?

**Comment by WoLfulus** [comment]
Not exactly, we were discussing yesterday if we'll be able to use eloquent models for Directus within the framework itself and how we'll target the models to the `system` connection (to support having Directus system tables in a separate database).

There's a case where there might be multiple instances of Directus too. 

`\Directus\Framework\Directus`

**Comment by WoLfulus** [comment]
This was solved implementing a trait that switches the connection for system models
