### ISSUE TITLE
[Fix] Some columns are set to `text` when it's supposed to be `json`

### ISSUE THREAD

**Issue by WoLfulus** [directus/api-next#151]
- Needs to update table creation migrations
- Needs to update system helper to forward a json value instead of text

**Comment by WoLfulus** [comment]
@rijkvanzanten

**Comment by rijkvanzanten** [comment]
Yup! Mentioned this in the PR too

When the original was made, there was no JSON type in MySQL yet

**Comment by WoLfulus** [comment]
Fixed in #156
