### ISSUE TITLE
postgres support?

### ISSUE THREAD

**Issue by shaunc** [directus/api-next#161]
It seems that https://github.com/directus/api/pull/1319 has concluded that you are not going to support postgres in the near term. Should I keep an eye on this project for postgres support? (Sigh -- I could have helped if you'd followed through and ported to typescript. :/)

**Comment by WoLfulus** [comment]
In theory we already have support for postgres as we now rely on eloquent/illuminate to connect to the database.

As for a typescript port, there is a plan to port directus to javascript in the long term too, we are doing the laravel migration to get the api stable enough to be maintainable.

**Comment by shaunc** [comment]
Ah -- great! There seem to be so many "headless CMS" projects out there; only yours is designed in a way we can use it. Hmm... 

> In theory we already have support for postgres

Don't you have to do some things -- like introspection -- that are a bit db specific? Or does `eloquent/illuminate` solve that too? Any pointers for giving it a whirl?

**Comment by WoLfulus** [comment]
I'm still studying this. (checking the differences and how each database work) I'm not sure if eloquent/illuminate supports this out of the box, but I already assumed that we're going to have to some interfaces to abstract the implementation for each database vendor (which also allows for registering custom implementation for different db vendors)

**Comment by shaunc** [comment]
Great -- thanks for the news. If/when you think you have something (commit, branch...) that might work, we're eager to give it a try.

**Comment by WoLfulus** [comment]
I'm closing this one :)

**Comment by shaunc** [comment]
Very good ... but do post if you want a tester! ;)
