### ISSUE TITLE
Typecasting middleware

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api-next#27]
The API should return values typecasted based on internal types. For example, JSON should be returned as a JSON object, not a TEXT string (based on DB driver), TINYINT booleans should be returned as `true` / `false` instead of `1` / `0` etc

**Comment by WoLfulus** [comment]
This is already being handled by the models. We just need to feed the proper data into `casts`. 

I'm closing this one for now, if we need we can reopen this later
