### ISSUE TITLE
Activity handler

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api-next#34]
Directus saves all activity in directus_activity for accountability. I think this should probably be handled on the core SDK level, so we can provide accountability for both events happened through the API as through the core SDK directly

**Comment by WoLfulus** [comment]
@rijkvanzanten I'm unsure if this is handled already or not @rijkvanzanten . What do you mean by core sdk level? In which case activity is not registered in the current codebase?

**Comment by rijkvanzanten** [comment]
It was just a suggestion of how to handle it in the new codebase. Seeing we want to store activity for nearly everything that happens, I figured it would be a good thing to have as global middleware

**Comment by WoLfulus** [comment]
As middleware it's really easy to miss out stuff, so I'd probably just raise events and install some listeners to create the corresponding entries to activity instead. Seeing that directus could be used programatically in a custom route, this would be better

**Comment by rijkvanzanten** [comment]
Cool, whatever works best 👍
