### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api-next#64]
User needs to be able to provide custom code that runs on given event.

There's two types of hooks: actions and filters

Actions are arbitrary code that runs on a given action.

A filter allows the user to filter the data going in and coming out of the API

https://docs.directus.io/extensions/hooks.html#creating-hooks

**Comment by jooola** [comment]
Hooks should allow to be configured with a threshold, timeout and active after configuration values.

Here is a common example:

We have a static website that render content statically. For instance a blog post.
All CRUD operation on a blog post might trigger a hook that will build the new website on a remote server (CI).

If an item gets updated 3 times in row, we don't want to trigger the build server 3 times. This means we should allow a threshold, some timeout and an active after configuration.

threshold : 10s
timeout: 10s
activeAfter: 10s

0s -> Item updated -> start 10s threshold 
+ 5 s -> Item updated -> restart 10 seconds threshold
+ 5 s -> Item updated -> timeout exceeded, ignore threshold -> run Hook
+ 5 s -> item updated -> hook not active after 10s, ignore hook
+ 5 s -> item updated -> hook active, start 10s threshold
-> threshold elapsed => run hook

**Comment by jooola** [comment]
Any chances to break compatibility with this one ?

**Comment by jooola** [comment]
Woups sorry for the double post...

Many people as to be able to trigger a hook for multiple events.

**Comment by WoLfulus** [comment]
I think this behavior can be implemented in the hook itself. Hooks are like
events, they should happen everytime, having this in place I think its
kinda out of scope, but this debounce can be implemented outside of hooks.

We'll for sure take a look at this when it's time. :)

Em sáb, 7 de mar de 2020 19:36, Jonas L. <notifications@github.com>
escreveu:

**Comment by WoLfulus** [comment]
For the sake of simplicity we're using laravel's event handlers for hooks. It's a matter of registering the right hooks from now on.
